// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Severity = ("INFO" | "WARNING" | "ERROR")

export interface Variables {
  editorFileContent: EditorFileContent;
  knownVariables: KnownVariables;
  validationResult: ValidationResult[];
  variablesData: VariablesData;
  variablesEditorDataContext: VariablesEditorDataContext;
  variablesSaveDataArgs: VariablesSaveDataArgs;
  [k: string]: unknown;
}
export interface EditorFileContent {
  content: string;
}
export interface KnownVariables {
  children: KnownVariables[];
  description: string;
  metaData: MetaData | FileMetaData | EnumMetaData;
  name: string;
  namespace: string;
  value: string;
}
export interface MetaData {
  type: string;
}
export interface FileMetaData {
  extension: string;
  type: "file";
}
export interface EnumMetaData {
  type: "enum";
  values: string[];
}
export interface ValidationResult {
  message: string;
  path: string;
  severity: Severity;
}
export interface VariablesData {
  context: VariablesEditorDataContext;
  data: string;
  helpUrl: string;
}
export interface VariablesEditorDataContext {
  app: string;
  file: string;
  pmv: string;
}
export interface VariablesSaveDataArgs {
  context: VariablesEditorDataContext;
  data: string;
}
